### ISSUE TITLE
MMR mutations and MSI status

### ISSUE THREAD

**Issue by asaki1986** [xjtu-omics/msisensor-pro#10]
Hi,

MSISensor-pro did provide a large convenience to determine the MSI status for tumor-only samples by building the baseline of PON.

According to our knowledge, pathogenic mutations in MMR gene, such as MLH1, MSH2, MSH6, PMS2, can result in deficient MMR gene function, which will finally lead to MSI-H for these samples.

However, we found some samples harbor these  pathogenic variants, but remained stable for most MSI sites.

Any suggestion to review/plot the peaks of these sites without wet experiments (since these data were fetched from public resource), so that we can understand the underlying mechanism behind?

Thanks,
Junfeng

**Comment by PengJia6** [comment]
> Hi,
> 
> MSISensor-pro did provide a large convenience to determine the MSI status for tumor-only samples by building the baseline of PON.
> 
> According to our knowledge, pathogenic mutations in MMR gene, such as MLH1, MSH2, MSH6, PMS2, can result in deficient MMR gene function, which will finally lead to MSI-H for these samples.
> 
> However, we found some samples harbor these pathogenic variants, but remained stable for most MSI sites.
> 
> Any suggestion to review/plot the peaks of these sites without wet experiments (since these data were fetched from public resource), so that we can understand the underlying mechanism behind?
> 
> Thanks,
> Junfeng

Hi Junfeng, 

Thanks for your question! I am sorry I cannot give an authoritative suggestion. But I think the deficient MMR gene function may be leaded by a higher level mutaiton ratiao than you observe. Is it possibel?  If you have many samples, you can explore the correlation between MSI-score by MSIsensor-pro and the number of pathogenic variants in MRR genes. Hope this helps!

best,
Peng
