### ISSUE TITLE
MSI score greater than 1

### ISSUE THREAD

**Issue by shanshenbing** [xjtu-omics/msisensor-pro#11]
I ran MSIsensor-pro with paired samples successfully and I found some sample has a MSI score great than 1. Actually, the MSI score is the percent of somatic sites, which can not be 1 or great than 1.  So, I am confused with the result. I hope you can give me some suggestions.
![25X(X8GVQDO$8K8TFKZBNH0](https://user-images.githubusercontent.com/42245493/89871000-4a61ae80-dbe9-11ea-8743-575962955b10.png)

**Comment by PengJia6** [comment]
> I ran MSIsensor-pro with paired samples successfully and I found some sample has a MSI score great than 1. Actually, the MSI score is the percent of somatic sites, which can not be 1 or great than 1. So, I am confused with the result. I hope you can give me some suggestions.
> ![25X(X8GVQDO$8K8TFKZBNH0](https://user-images.githubusercontent.com/42245493/89871000-4a61ae80-dbe9-11ea-8743-575962955b10.png)

Could you please send your command and output to me. My email is pengjia@stu.xjtu.edu.cn

Thanks !

**Comment by shanshenbing** [comment]
Sorry，It‘s my fault. I didn't notice that MSIsensor-pro output is  in percent and my data is just greater than 1%.  And I also run msisensor with my data and I found the MSI scores of the same sample are different.  Is this normal?

**Comment by PengJia6** [comment]
This is normal, but I don't think it matters. This may caused by the different default parameters between these two program.

**Comment by PengJia6** [comment]
> Sorry，It‘s my fault. I didn't notice that MSIsensor-pro output is in percent and my data is just greater than 1%. And I also run msisensor with my data and I found the MSI scores of the same sample are different. Is this normal?

This is normal, but I don't think it matters. This may caused by the different default parameters between these two programs.

**Comment by shanshenbing** [comment]
Thank you for your reply. The reason why I noticed the problem is that the difference is a little big.&nbsp;
I ran msisensor-pro scan with fasta file and using the generated file for next step.&nbsp;
The softwares werw run as follow:


nohup msisensor-pro msi -z 1&nbsp; -b 3 -0 1 -y 1&nbsp; &nbsp; -d /path_to/Homo_sapiens.GRCh37.75.format.list \
&nbsp; &nbsp; -t /path_to/${tumor}.reorder.sort.add.mkdup.BQSR.bam \
&nbsp; &nbsp; -n /path_to/${normal}.reorder.sort.add.mkdup.BQSR.bam&nbsp; \
&nbsp; &nbsp; -o ${WORK_DIR}/result/${sample}/${sample}&nbsp; &amp;



nohup msisensor msi -z 1&nbsp; -b 3&nbsp; -y 1&nbsp; &nbsp; -d /path_to/Homo_sapiens.GRCh37.75.format.list \
&nbsp; &nbsp; -t /path_to/${tumor}.reorder.sort.add.mkdup.BQSR.bam \
&nbsp; &nbsp; -n /path_to/${normal}.reorder.sort.add.mkdup.BQSR.bam&nbsp; \
&nbsp; &nbsp; -o ${WORK_DIR}/result/${sample}/${sample} &amp;

note: I used the same list file generated by msisensor-pro scan.


The result of first 35 samples is in the accessory, and I found the Pearson r is about 0.7 compulated with all my data.&nbsp; The parameters are similar to each other, but results are different. And I also found a relate issue at&nbsp;https://github.com/ding-lab/msisensor/issues/3.&nbsp;


I hope to get your advice.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjtu-omics/msisensor-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 晚上10:24
收件人:&nbsp;"xjtu-omics/msisensor-pro"<msisensor-pro@noreply.github.com&gt;;
抄送:&nbsp;"单申兵"<1186426740@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xjtu-omics/msisensor-pro] MSI score greater than 1 (#11)





 
This is normal, but I don't think it matters. This may caused by the different default parameters between these two program.

**Comment by PengJia6** [comment]
> The result of first 35 samples is in the accessory, and I found the Pearson r is about 0.7 compulated with all my data.&nbsp; The parameters are similar to each other, but results are different. And I also found a relate issue at&nbsp;[ding-lab/msisensor#3](https://github.com/ding-lab/msisensor/issues/3).&nbsp;

The _msi_ module in msisensor-pro is inherited from msisensor, the results should be same. Could you please add -c option to the two command and try again, because there is a small bug in the default parameter, please see [#8 ](https://github.com/xjtu-omics/msisensor-pro/issues/8).  
Please let me know if this is workable and feel free to contact me if you have any question.

**Comment by shanshenbing** [comment]
I wrote the last comment in QQ mailbox and the space character was converted into '&nbsp; '. I am sorry for the confusing meaning. I checked msisensor default parameters and found the default -c in msisensor is 20, so msisensor-pro was run with -c 20. The result of the two software are same.  Thank you for your help! Maybe the next release of msisensor-pro can change the default value of -c parameter.

**Comment by PengJia6** [comment]
@shanshenbing Thanks, I had updated source code and binary version, and conda version would be updated later. Thanks for using our software and give feedback, if you have other questions, please open a new issue or contact with me directly.
