### ISSUE TITLE
more documentation on what the outputs mean?

### ISSUE THREAD

**Issue by boyangzhao** [xjtu-omics/msisensor-pro#14]
Hello,

Can you guys provide a bit more info on what the outputs from the `msisensor-pro msi` results mean? I see there are the _prefix_, _dis, _germline, __somatic files. It would be helpful if there is some explanation in the documentation? The File Formats page only had a few lines describing the outputs. I'm interested in knowing if the tumor samples I have can be classified into MSI-H or MSS. Is the MSI score the third column % in the prefix file?  What is the # of somatic sites? is this the number of detected unstable sites (in somatic, and not found in germline)? 

Also, do you need multiple normal samples as baseline, or is this only for tumor-only and you can run with just a single matched tumor-normal pair?

Bo

**Comment by PengJia6** [comment]
Hi Bo @boyangzhao ,

I will provide more information about the output in Wiki. The MSI score is the third column(%) in the prefix file. Number_of_Somatic_Sites is this the number of detected unstable sites. 

If you have tumor and its matched normal sample, I suggest you use the **_msi_** command (msisensor oringal version).   If you have only tumor sample, you need build a baseline and run _**pro**_ command. 

Peng

**Comment by boyangzhao** [comment]
Ah great! Thanks!!

**Comment by anoronh4** [comment]
Looking forward to this as well. I am interested in knowing the definitions of each column in the `_germline` and `_somatic` files

**Comment by Huanan2018** [comment]
Hello,
I am also interested in knowing the definitions of each column in the _germline and _somatic files. Has this part of the documentation been updated on the wiki?
Another question, why is the total number of microsatellite loci in the report not equal to the number of microsatellites in gemerline? Is this process filtered?

**Comment by PengJia6** [comment]
see https://github.com/xjtu-omics/msisensor-pro/blob/master/docs/5_files_type.md
