### ISSUE TITLE
how to select the msi site for a target panel

### ISSUE THREAD

**Issue by worker000000** [xjtu-omics/msisensor-pro#17]
Dear professor,
as you can see, target panel especially some small panels are economic for clinic, so is there a the least msi sites for a panel, is there any suggeestion about this?
thanks a lot

**Comment by PengJia6** [comment]
> as you can see, target panel especially some small panels are economic for clinic, so is there a the least msi sites for a panel, is there any suggeestion about this? 

Hi, 

Sorry for  late response! 

We have some recommended msi sites for panel in clinical. We are very willing to help you. Please contact me (pengjia@stu.xjtu.edu.cn) or Kai Ye (kaiye@xjtu.edu.cn) to get more details by email.

Best,

Peng
