### ISSUE TITLE
Missing dependency in readme

### ISSUE THREAD

**Issue by barslmn** [xjtu-omics/msisensor-pro#19]
Hey,

I needed to install `libcurl4-openssl-dev` on ubuntu 20.04. You might want to add it to your readme.

Thanks

**Comment by PengJia6** [comment]
> Hey,
> 
> I needed to install `libcurl4-openssl-dev` on ubuntu 20.04. You might want to add it to your readme.
> 
> Thanks

Thanks a lot！We have add it to Readme and wiki.
