### ISSUE TITLE
bam index issue of baseline option

### ISSUE THREAD

**Issue by asaki1986** [xjtu-omics/msisensor-pro#2]
Hi,

I found the sample.bai that was generate from GATK can not be directly loaded in msisensor-pro baseline option. Rather, it required a sample.bam.bai that newly generated by samtools.

`[bam_index_load] fail to load BAM index.
msisensor-pro: bamreader.cpp:172: bool ReadInBamReads(const char*, const string&, unsigned int, unsigned int, std::vector<SPLIT_READ>&, std::string): Assertion `idx' failed.`

However, this kind of index file can be loaded when "msisensor-pro pro" command is applied.

It will be great of help if you can offer a solution.

Thanks

**Comment by PengJia6** [comment]
Hi, 
Thanks for your question. The `sample.bam` and `sample.bam.bai`  should be pleased in the same location. By the way, if your bam file is generated by GATK, you may have a index file like `sample.bai`. If that, you can use the symbol link command to generate a sample.bam.bai file. 
  ` ls -s sample.bai sample.bam.bai `  Please let me know, if it is worked, and we will fixed this bug in next release.

**Comment by asaki1986** [comment]
> Hi,
> Thanks for your question. The `sample.bam` and `sample.bam.bai` should be pleased in the same location. By the way, if your bam file is generated by GATK, you may have a index file like `sample.bai`. If that, you can use the symbol link command to generate a sample.bam.bai file.
> `ls -s sample.bai sample.bam.bai` Please let me know, if it is worked, and we will fixed this bug in next release.

Hi,

I tried the ln -s option, but not worked.

**Comment by PengJia6** [comment]
Hi, 
I am sorry to here that. I try msisensor-pro pro using bam file gererated by gatk just now, it worked in my envirorment. 
Could you please update the msisensor-pro using `conda install msisensor-pro`.
You can also check your bam file using samtools quickcheck to make sure the completion of your bam file.  
If it is also not worked, please offer you gatk  and msisensor-pro scripts.
Thank you!

**Comment by arielyh** [comment]
Hi Peng,

I had similar issues. Here is my command and results:
(msisensor-env) [myid@compute-a-xx-xxx msisensor_test]$ msisensor-pro baseline -d hg19_msi_reference.list -i configure.txt -o .
baseline -d hg19_msi_reference.list -i configure.txt -o . 

Check for the environment ...
Current work path: /home/myid/msisensor_test
Microsatellites file: /home/myid/msisensor_test/hg19_msi_reference.list
Configure file path: /home/myid/msisensor_test/configure.txt
Output path:/home/myid/msisensor_test
/home/myid/msisensor_test/ is existing! OK!
/home/myid/msisensor_test/detail is existing! OK!

Load files ...
load bam:/home/myid/msisensor_test/normal/case1_sorted.bam OK!
load bam:/home/myid/msisensor_test/normal/case2_sorted.bam OK!
Open bam file failed(  ), please provide valid bam file with its index file !

However, I have both the .bam and .bai files under the normal folder. I've also checked the bam files using samtools and they are correct with completed EOF.  I tried both case1_sorted.bam.bai and case1_sorted.bai, but neither of them worked for me.
