### ISSUE TITLE
MSISensor distribution file only has 10+ base repeats. Where are datapoints for di-tri-quad-penta, etc repeats?

### ISSUE THREAD

**Issue by ranasats** [xjtu-omics/msisensor-pro#21]
I'm looking at MSI Sensor output distribution file. 

All of the lines in my output are at minimum 10 base repeats, but nothing that are 2 to 9 base repeats.

For example:

`1 993467 GTTTC 10[A] TGAAA `

is the smallest base pair repeat that is in the distribution file. There are none that are 9bp and below

Is there anyway to get this data?

**Comment by PengJia6** [comment]
@ranasats  please set  -l option when you use _**scan**_ and _**msi**_ module!

**Comment by ruolin** [comment]
I have the same problem. The `-l` option is disabled in `msisensor pro`, line 480 here https://github.com/xjtu-omics/msisensor-pro/blob/master/cpp/distribution.cpp#L480. The `-p` does not change the lower bound. Also, it is not clear to me what is the difference between `MininalHomoForDis` and `MininalHomoSize`.

**Comment by PengJia6** [comment]
I apologize for the delayed response. If you are still using it, please check version 1.3.0; this issue should have been resolved.
