### ISSUE TITLE
Can macOS use msisensor-pro?

### ISSUE THREAD

**Issue by lancermiss** [xjtu-omics/msisensor-pro#22]

**Comment by PengJia6** [comment]
@lancermiss  

Yes, you can install msisensor-pro on your macOS  by [bioconda](https://github.com/xjtu-omics/msisensor-pro/wiki/How-to-install-MSIsensor-pro#install-using--bioconda), [docker](https://github.com/xjtu-omics/msisensor-pro/wiki/How-to-install-MSIsensor-pro#install-using-docker) or [build by your self](https://github.com/xjtu-omics/msisensor-pro/wiki/How-to-install-MSIsensor-pro#install-from-source-code).   

Please feel free to contact me, if you have any questions for usage of msisensor-pro on macOS.
