### ISSUE TITLE
docker image has error while loading libraries

### ISSUE THREAD

**Issue by anoronh4** [xjtu-omics/msisensor-pro#23]
I am trying to run msisensor using the dockerhub image `pengjia1110/msisensor-pro:latest`. i am running with singularity v 3.3.0 and getting the following error:
```
$ singularity exec ./msisensor-pro_latest.sif msisensor-pro
msisensor-pro: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory
```
i get this error regardless of whether i use the singularity option `-e` for a clean environment. maybe something is missing in the container because it was present in the host environment during testing?

**Comment by PengJia6** [comment]
@anoronh4  Sorry for the late reply. We just test the msisensor-pro with docker. It seems htslib is missed in the container, but I do not meet this in docker. I will test it in singularity and give you a feedback as soon as possible.

**Comment by sscien** [comment]
Hi Peng, have you resolved this htslib issue?

**Comment by PengJia6** [comment]
@sscien  Sorry, I can not install singularity  version in our HPC, but the conda and docker version is OK.

**Comment by iranmdl** [comment]
Hi! I am having the same issue when converting docker image to singularity (unfortunately I cannot use docker or conda). Any updates on this?

**Comment by PengJia6** [comment]
@iranmdl  Thanks for your contributions！ I will test and update the dockerfile.

**Comment by oliverartz** [comment]
Hi @PengJia6, did you end up fixing the docker? I am running into the same issues as @anoronh4. Is there a solution for this?

**Comment by gudeqing** [comment]
I also got this same issue using the latest image using cwltool,  and the reason is that the “/tmp” directory is replaced by cwltool
