### ISSUE TITLE
Program aborted:Same reference genome file should be used in both 'scan' and msi/pro/baseline steps

### ISSUE THREAD

**Issue by Zho-o-o-u** [xjtu-omics/msisensor-pro#25]
Hello, When I use the docker to run msisensor-pro, at the baseline(for tumor only samples), the terminal shows:Program aborted:Same reference genome file should be used in both 'scan' and msi/pro/baseline steps. In the step of scan, I used GRCh38.d1.vd1.fa to generate reference.list.

=====here is full result=====================================================================
Test with bam input
baseline -d /data/reference/reference.list -i /data/data4baseline/baseline.bam.configure4docker -o /data/output/tumor_normal/tumor_only_bam Start at:  Wed Mar 31 04:39:26 2021

Check for the environment ... 
Current work path: /
Microsatellites file: /data/reference/reference.list
Configure file path: /data/data4baseline/baseline.bam.configure4docker
Output path:/data/output/tumor_normal/tumor_only_bam
/data/output/tumor_normal/tumor_only_bam/ is existing! OK!
/data/output/tumor_normal/tumor_only_bam/detail is existing! OK!

Load files ... 
/data/data4baseline/bamForTumorOnlyBaseLine/case1_normal_sorted.bam  case1
/data/data4baseline/bamForTumorOnlyBaseLine/case1_normal_sorted.bam  case1
load bam:/data/data4baseline/bamForTumorOnlyBaseLine/case1_normal_sorted.bam OK!
/data/data4baseline/bamForTumorOnlyBaseLine/case2_normal_sorted.bam  case2
/data/data4baseline/bamForTumorOnlyBaseLine/case2_normal_sorted.bam  case2
load bam:/data/data4baseline/bamForTumorOnlyBaseLine/case2_normal_sorted.bam OK!
/data/data4baseline/bamForTumorOnlyBaseLine/case3_normal_sorted.bam  case3
/data/data4baseline/bamForTumorOnlyBaseLine/case3_normal_sorted.bam  case3
load bam:/data/data4baseline/bamForTumorOnlyBaseLine/case3_normal_sorted.bam OK!
Loading homopolymer and microsatellite sites ... 
Total loading windows:  7123  !OK 
Total loading homopolymer and microsatellites:  1806147    !OK 

Process the 1 case : case1 /data/data4baseline/bamForTumorOnlyBaseLine/case1_normal_sorted.bam
    Process 1 case1 window: 0 done...:chr1:25453-524883
    Process 1 case1 window: 1 done...:chr1:527455-1029320
    Process 1 case1 window: 2 done...:chr1:1028590-1528958
    Process 1 case1 window: 3 done...:chr1:1529828-2027833
    Process 1 case1 window: 4 done...:chr1:2041044-2542469
    Process 1 case1 window: 5 done...:chr1:2547807-3042997
    Process 1 case1 window: 6 done...:chr1:3050534-3539696
    Process 1 case1 window: 7 done...:chr1:3554158-4055367
    Process 1 case1 window: 8 done...:chr1:4055250-4556668
    Process 1 case1 window: 9 done...:chr1:4559995-5053554
    Process 1 case1 window: 10 done...:chr1:5062293-5562861
    Process 1 case1 window: 11 done...:chr1:5562358-6064030
    Process 1 case1 window: 12 done...:chr1:6062409-6562714
    Process 1 case1 window: 13 done...:chr1:6566563-7068418
    Process 1 case1 window: 14 done...:chr1:7074662-7570620
    Process 1 case1 window: 15 done...:chr1:7575000-8075874
    Process 1 case1 window: 16 done...:chr1:8075744-8577216
    Process 1 case1 window: 17 done...:chr1:8576162-9077795
    Process 1 case1 window: 18 done...:chr1:9076398-9576212
    Process 1 case1 window: 19 done...:chr1:9579854-10081429
    Process 1 case1 window: 20 done...:chr1:10080063-10581782
    Process 1 case1 window: 21 done...:chr1:10580305-11081564
    Process 1 case1 window: 22 done...:chr1:11081079-11578399
    Process 1 case1 window: 23 done...:chr1:11581298-12082657
    Process 1 case1 window: 24 done...:chr1:12081549-12577561
    Process 1 case1 window: 25 done...:chr1:12581839-13082508
    Process 1 case1 window: 26 done...:chr1:13081924-13581644
    Process 1 case1 window: 27 done...:chr1:13585763-14085920
    Process 1 case1 window: 28 done...:chr1:14086994-14588447
    Process 1 case1 window: 29 done...:chr1:14588331-15088399
    Process 1 case1 window: 30 done...:chr1:15088732-15590020
    Process 1 case1 window: 31 done...:chr1:15589835-16091093
    Process 1 case1 window: 32 done...:chr1:16092251-16589441
    Process 1 case1 window: 33 done...:chr1:16593002-17094080
    Process 1 case1 window: 34 done...:chr1:17099660-17600351
    Process 1 case1 window: 35 done...:chr1:17600049-18099391
    Process 1 case1 window: 36 done...:chr1:18100391-18601812
    Process 1 case1 window: 37 done...:chr1:18601691-19103362
    Process 1 case1 window: 38 done...:chr1:19104529-19604331
    Process 1 case1 window: 39 done...:chr1:19605749-20105636
    Process 1 case1 window: 40 done...:chr1:20107588-20609393
    Process 1 case1 window: 41 done...:chr1:20608485-21109902
    Process 1 case1 window: 42 done...:chr1:21109300-21610391
    Process 1 case1 window: 43 done...:chr1:21614399-22112466
    Process 1 case1 window: 44 done...:chr1:22118060-22619040
    Process 1 case1 window: 45 done...:chr1:22619601-23121371
    Process 1 case1 window: 46 done...:chr1:23121022-23622251
    Process 1 case1 window: 47 done...:chr1:23621302-24120750
    Process 1 case1 window: 48 done...:chr1:24121797-24622967
    Process 1 case1 window: 49 done...:chr1:24621896-25123622
    Process 1 case1 window: 50 done...:chr1:25122191-25622631
    Process 1 case1 window: 51 done...:chr1:25623998-26124176
    Process 1 case1 window: 52 done...:chr1:26124504-26626451
    Process 1 case1 window: 53 done...:chr1:26626403-27126237
    Process 1 case1 window: 54 done...:chr1:27127657-27629516
    Process 1 case1 window: 55 done...:chr1:27628074-28129293
    Process 1 case1 window: 56 done...:chr1:28128880-28629675
    Process 1 case1 window: 57 done...:chr1:28629551-29128426
    Process 1 case1 window: 58 done...:chr1:29130806-29632659
    Process 1 case1 window: 59 done...:chr1:29636619-30138386
    Process 1 case1 window: 60 done...:chr1:30138318-30638037
    Process 1 case1 window: 61 done...:chr1:30643862-31144971
    Process 1 case1 window: 62 done...:chr1:31144080-31641762
    Process 1 case1 window: 63 done...:chr1:31647130-32148650
    Process 1 case1 window: 64 done...:chr1:32147557-32649038
    Process 1 case1 window: 65 done...:chr1:32647963-33145135
    Process 1 case1 window: 66 done...:chr1:33148458-33649361
    Process 1 case1 window: 67 done...:chr1:33651183-34151079
    Process 1 case1 window: 68 done...:chr1:34153727-34654989
    Process 1 case1 window: 69 done...:chr1:34659132-35161046
    Process 1 case1 window: 70 done...:chr1:35159299-35659876
    Process 1 case1 window: 71 done...:chr1:35660186-36160035
    Process 1 case1 window: 72 done...:chr1:36160863-36659435
    Process 1 case1 window: 73 done...:chr1:36661232-37162293
    Process 1 case1 window: 74 done...:chr1:37162313-37663975
    Process 1 case1 window: 75 done...:chr1:37663320-38145781
    Process 1 case1 window: 76 done...:chr1:38163398-38662597
    Process 1 case1 window: 77 done...:chr1:38663959-39164340
    Process 1 case1 window: 78 done...:chr1:39165071-39665852
    Process 1 case1 window: 79 done...:chr1:39666196-40163184
    Process 1 case1 window: 80 done...:chr1:40167041-40661378
    Process 1 case1 window: 81 done...:chr1:40667249-41168912
    Process 1 case1 window: 82 done...:chr1:41167632-41667143
    Process 1 case1 window: 83 done...:chr1:41675060-42176136
    Process 1 case1 window: 84 done...:chr1:42176756-42677760
    Process 1 case1 window: 85 done...:chr1:42681905-43181223
    Process 1 case1 window: 86 done...:chr1:43183740-43679587
    Process 1 case1 window: 87 done...:chr1:43684455-44186429
    Process 1 case1 window: 88 done...:chr1:44185337-44686634
    Process 1 case1 window: 89 done...:chr1:44685679-45187593
    Process 1 case1 window: 90 done...:chr1:45188320-45689903
    Process 1 case1 window: 91 done...:chr1:45688995-46187664
    Process 1 case1 window: 92 done...:chr1:46189097-46682963
    Process 1 case1 window: 93 done...:chr1:46692687-47192445
    Process 1 case1 window: 94 done...:chr1:47198604-47695863
    Process 1 case1 window: 95 done...:chr1:47699692-48201417
    Process 1 case1 window: 96 done...:chr1:48202170-48700940
    Process 1 case1 window: 97 done...:chr1:48706296-49207859
    Process 1 case1 window: 98 done...:chr1:49206542-49708367
    Process 1 case1 window: 99 done...:chr1:49713569-50214662
    Process 1 case1 window: 100 done...:chr1:50215071-50715347
    Process 1 case1 window: 101 done...:chr1:50716987-51218836
    Process 1 case1 window: 102 done...:chr1:51217128-51718675
    Process 1 case1 window: 103 done...:chr1:51718445-52215669
    Process 1 case1 window: 104 done...:chr1:52218647-52719644
    Process 1 case1 window: 105 done...:chr1:52718747-53217771
    Process 1 case1 window: 106 done...:chr1:53222052-53723830
    Process 1 case1 window: 107 done...:chr1:53722239-54222702
    Process 1 case1 window: 108 done...:chr1:54223941-54725432
    Process 1 case1 window: 109 done...:chr1:54726055-55227997
    Process 1 case1 window: 110 done...:chr1:55227524-55729392
    Process 1 case1 window: 111 done...:chr1:55727846-56229430
    Process 1 case1 window: 112 done...:chr1:56228960-56727950
    Process 1 case1 window: 113 done...:chr1:56729283-57230516
    Process 1 case1 window: 114 done...:chr1:57229320-57730894
    Process 1 case1 window: 115 done...:chr1:57730804-58227396
    Process 1 case1 window: 116 done...:chr1:58231476-58731564
    Process 1 case1 window: 117 done...:chr1:58732141-59232685
    Process 1 case1 window: 118 done...:chr1:59235289-59737103
    Process 1 case1 window: 119 done...:chr1:59740938-60241261
    Process 1 case1 window: 120 done...:chr1:60242181-60740376
    Process 1 case1 window: 121 done...:chr1:60742967-61241970
    Process 1 case1 window: 122 done...:chr1:61245604-61747094
    Process 1 case1 window: 123 done...:chr1:61747246-62248304
    Process 1 case1 window: 124 done...:chr1:62247547-62748717
    Process 1 case1 window: 125 done...:chr1:62748386-63248686
    Process 1 case1 window: 126 done...:chr1:63248645-63740404
    Process 1 case1 window: 127 done...:chr1:63748843-64250377
    Process 1 case1 window: 128 done...:chr1:64250179-64751307
    Process 1 case1 window: 129 done...:chr1:64752523-65254352
    Process 1 case1 window: 130 done...:chr1:65253467-65751490
    Process 1 case1 window: 131 done...:chr1:65754368-66242725
    Process 1 case1 window: 132 done...:chr1:66260354-66754153
    Process 1 case1 window: 133 done...:chr1:66764640-67264863
    Process 1 case1 window: 134 done...:chr1:67264873-67765701
    Process 1 case1 window: 135 done...:chr1:67765106-68265698
    Process 1 case1 window: 136 done...:chr1:68265929-68767107
    Process 1 case1 window: 137 done...:chr1:68766601-69268048
    Process 1 case1 window: 138 done...:chr1:69271065-69767035
    Process 1 case1 window: 139 done...:chr1:69775716-70276961
    Process 1 case1 window: 140 done...:chr1:70275849-70776948
    Process 1 case1 window: 141 done...:chr1:70776057-71276647
    Process 1 case1 window: 142 done...:chr1:71280161-71781040
    Process 1 case1 window: 143 done...:chr1:71781991-72283938
    Process 1 case1 window: 144 done...:chr1:72282126-72779024
    Process 1 case1 window: 145 done...:chr1:72788757-73290523
    Process 1 case1 window: 146 done...:chr1:73289640-73787984
    Process 1 case1 window: 147 done...:chr1:73792193-74292155
    Process 1 case1 window: 148 done...:chr1:74295273-74794251
    Process 1 case1 window: 149 done...:chr1:74801548-75303112
    Process 1 case1 window: 150 done...:chr1:75303074-75802710
    Process 1 case1 window: 151 done...:chr1:75803499-76303053
    Process 1 case1 window: 152 done...:chr1:76305668-76806706
    Process 1 case1 window: 153 done...:chr1:76812057-77313611
    Process 1 case1 window: 154 done...:chr1:77313411-77813443
    Process 1 case1 window: 155 done...:chr1:77816955-78318862
    Process 1 case1 window: 156 done...:chr1:78325227-78826991
    Process 1 case1 window: 157 done...:chr1:78827189-79326604
    Process 1 case1 window: 158 done...:chr1:79328481-79825567
    Process 1 case1 window: 159 done...:chr1:79831891-80333561
    Process 1 case1 window: 160 done...:chr1:80333298-80834033
    Process 1 case1 window: 161 done...:chr1:80838272-81340037
    Process 1 case1 window: 162 done...:chr1:81338382-81837817
    Process 1 case1 window: 163 done...:chr1:81838742-82339968
    Process 1 case1 window: 164 done...:chr1:82339477-82840784
    Process 1 case1 window: 165 done...:chr1:82839812-83340019
    Process 1 case1 window: 166 done...:chr1:83341360-83833252
    Process 1 case1 window: 167 done...:chr1:83842881-84339432
    Process 1 case1 window: 168 done...:chr1:84343078-84842998
    Process 1 case1 window: 169 done...:chr1:84846360-85346334
    Process 1 case1 window: 170 done...:chr1:85350060-85852024
    Process 1 case1 window: 171 done...:chr1:85851102-86345224
    Process 1 case1 window: 172 done...:chr1:86352417-86853400
    Process 1 case1 window: 173 done...:chr1:86852679-87348460
    Process 1 case1 window: 174 done...:chr1:87356223-87856447
    Process 1 case1 window: 175 done...:chr1:87856983-88353795
    Process 1 case1 window: 176 done...:chr1:88357038-88857804
    Process 1 case1 window: 177 done...:chr1:88857867-89356438
    Process 1 case1 window: 178 done...:chr1:89360079-89861786
    Process 1 case1 window: 179 done...:chr1:89862533-90362174
    Process 1 case1 window: 180 done...:chr1:90362624-90864423
    Process 1 case1 window: 181 done...:chr1:90863076-91364524
    Process 1 case1 window: 182 done...:chr1:91363192-91862857
    Process 1 case1 window: 183 done...:chr1:91864202-92362142
    Process 1 case1 window: 184 done...:chr1:92364980-92866440
    Process 1 case1 window: 185 done...:chr1:92865957-93365851
    Process 1 case1 window: 186 done...:chr1:93366008-93863097
    Process 1 case1 window: 187 done...:chr1:93866143-94364740
    Process 1 case1 window: 188 done...:chr1:94372307-94873411
    Process 1 case1 window: 189 done...:chr1:94877260-95379141
    Process 1 case1 window: 190 done...:chr1:95377639-95879636
    Process 1 case1 window: 191 done...:chr1:95877659-96379229
    Process 1 case1 window: 192 done...:chr1:96385759-96887484
    Process 1 case1 window: 193 done...:chr1:96891435-97393361
    Process 1 case1 window: 194 done...:chr1:97392291-97893087
    Process 1 case1 window: 195 done...:chr1:97892429-98392567
    Process 1 case1 window: 196 done...:chr1:98394487-98894618
    Process 1 case1 window: 197 done...:chr1:98895020-99392033
    Process 1 case1 window: 198 done...:chr1:99405711-99906372
    Process 1 case1 window: 199 done...:chr1:99907210-100407930
    Process 1 case1 window: 200 done...:chr1:100409210-100910043
    Process 1 case1 window: 201 done...:chr1:100911714-101413063
    Process 1 case1 window: 202 done...:chr1:101415062-101916364
    Process 1 case1 window: 203 done...:chr1:101916417-102417323
    Process 1 case1 window: 204 done...:chr1:102416750-102915914
    Process 1 case1 window: 205 done...:chr1:102922434-103422579
    Process 1 case1 window: 206 done...:chr1:103422463-103917504
    Process 1 case1 window: 207 done...:chr1:103929737-104431669
    Process 1 case1 window: 208 done...:chr1:104433805-104926787
    Process 1 case1 window: 209 done...:chr1:104943598-105445229
    Process 1 case1 window: 210 done...:chr1:105445674-105940890
    Process 1 case1 window: 211 done...:chr1:105946872-106446541
    Process 1 case1 window: 212 done...:chr1:106446885-106945199
    Process 1 case1 window: 213 done...:chr1:106949467-107450720
    Process 1 case1 window: 214 done...:chr1:107450108-107949841
    Process 1 case1 window: 215 done...:chr1:107950183-108450416
    Process 1 case1 window: 216 done...:chr1:108451948-108953800
    Process 1 case1 window: 217 done...:chr1:108953010-109454911
    Process 1 case1 window: 218 done...:chr1:109455446-109956622
    Process 1 case1 window: 219 done...:chr1:109958345-110460256
    Process 1 case1 window: 220 done...:chr1:110458774-110960736
    Process 1 case1 window: 221 done...:chr1:110959330-111458312
    Process 1 case1 window: 222 done...:chr1:111459342-111961042
    Process 1 case1 window: 223 done...:chr1:111964438-112464602
    Process 1 case1 window: 224 done...:chr1:112464445-112966442
    Process 1 case1 window: 225 done...:chr1:112964684-113461812
    Process 1 case1 window: 226 done...:chr1:113468513-113967836
    Process 1 case1 window: 227 done...:chr1:113968903-114467040
    Process 1 case1 window: 228 done...:chr1:114469638-114971511
    Process 1 case1 window: 229 done...:chr1:114974333-115475164
    Process 1 case1 window: 230 done...:chr1:115476590-115977305
    Process 1 case1 window: 231 done...:chr1:115978976-116480193
    Process 1 case1 window: 232 done...:chr1:116479960-116974604
    Process 1 case1 window: 233 done...:chr1:116982498-117483514
    Process 1 case1 window: 234 done...:chr1:117487213-117983241
    Process 1 case1 window: 235 done...:chr1:117994153-118494758
    Process 1 case1 window: 236 done...:chr1:118496540-118997997
    Process 1 case1 window: 237 done...:chr1:118998555-119494351
    Process 1 case1 window: 238 done...:chr1:119503461-120004373
    Process 1 case1 window: 239 done...:chr1:120003780-120503289
    Process 1 case1 window: 240 done...:chr1:120507455-121008428
    Process 1 case1 window: 241 done...:chr1:121013231-121513317
    Process 1 case1 window: 242 done...:chr1:121514242-121925662
    Process 1 case1 window: 243 done...:chr1:122101394-122230884
    Process 1 case1 window: 244 done...:chr1:123434176-123757876
    Process 1 case1 window: 245 done...:chr1:124123576-124260962
    Process 1 case1 window: 246 done...:chr1:124838519-125147418
    Process 1 case1 window: 247 done...:chr1:143276353-143775732
    Process 1 case1 window: 248 done...:chr1:143778873-144278504
    Process 1 case1 window: 249 done...:chr1:144279206-144780971
    Process 1 case1 window: 250 done...:chr1:144781896-145282779
    Process 1 case1 window: 251 done...:chr1:145283820-145784832
    Process 1 case1 window: 252 done...:chr1:145786571-146286827
    Process 1 case1 window: 253 done...:chr1:146287090-146788367
    Process 1 case1 window: 254 done...:chr1:146787703-147289325
    Process 1 case1 window: 255 done...:chr1:147292310-147793404
    Process 1 case1 window: 256 done...:chr1:147795494-148294603
    Process 1 case1 window: 257 done...:chr1:148298823-148800204
    Process 1 case1 window: 258 done...:chr1:148798840-149300801
    Process 1 case1 window: 259 done...:chr1:149300181-149799618
    Process 1 case1 window: 260 done...:chr1:149802520-150302624
    Process 1 case1 window: 261 done...:chr1:150303311-150803278
    Process 1 case1 window: 262 done...:chr1:150804209-151305829
    Process 1 case1 window: 263 done...:chr1:151306074-151807057
    Process 1 case1 window: 264 done...:chr1:151809533-152302938
    Process 1 case1 window: 265 done...:chr1:152313865-152808078
    Process 1 case1 window: 266 done...:chr1:152813999-153313602
    Process 1 case1 window: 267 done...:chr1:153323866-153825758
    Process 1 case1 window: 268 done...:chr1:153825006-154323489
    Process 1 case1 window: 269 done...:chr1:154327543-154829344
    Process 1 case1 window: 270 done...:chr1:154833141-155334050
    Process 1 case1 window: 271 done...:chr1:155333437-155834646
    Process 1 case1 window: 272 done...:chr1:155834463-156335239
    Process 1 case1 window: 273 done...:chr1:156335280-156831550
    Process 1 case1 window: 274 done...:chr1:156837375-157337739
    Process 1 case1 window: 275 done...:chr1:157338783-157838771
    Process 1 case1 window: 276 done...:chr1:157844411-158346304
    Process 1 case1 window: 277 done...:chr1:158344728-158846219
    Process 1 case1 window: 278 done...:chr1:158845622-159346187
    Process 1 case1 window: 279 done...:chr1:159347936-159843814
    Process 1 case1 window: 280 done...:chr1:159851160-160351712
    Process 1 case1 window: 281 done...:chr1:160357908-160859084
    Process 1 case1 window: 282 done...:chr1:160858743-161360096
    Process 1 case1 window: 283 done...:chr1:161359028-161855871
    Process 1 case1 window: 284 done...:chr1:161859183-162358097
    Process 1 case1 window: 285 done...:chr1:162360277-162861562
    Process 1 case1 window: 286 done...:chr1:162860401-163360848
    Process 1 case1 window: 287 done...:chr1:163362405-163860524
    Process 1 case1 window: 288 done...:chr1:163864212-164366096
    Process 1 case1 window: 289 done...:chr1:164364463-164859447
    Process 1 case1 window: 290 done...:chr1:164869191-165366472
    Process 1 case1 window: 291 done...:chr1:165369333-165871201
    Process 1 case1 window: 292 done...:chr1:165870729-166372135
    Process 1 case1 window: 293 done...:chr1:166371113-166872521
    Process 1 case1 window: 294 done...:chr1:166871673-167368794
    Process 1 case1 window: 295 done...:chr1:167371929-167873367
    Process 1 case1 window: 296 done...:chr1:167872074-168369528
    Process 1 case1 window: 297 done...:chr1:168372960-168873474
    Process 1 case1 window: 298 done...:chr1:168873415-169375202
    Process 1 case1 window: 299 done...:chr1:169374321-169871755
    Process 1 case1 window: 300 done...:chr1:169875095-170376942
    Process 1 case1 window: 301 done...:chr1:170375324-170876476
    Process 1 case1 window: 302 done...:chr1:170878059-171372882
    Process 1 case1 window: 303 done...:chr1:171378618-171879837
    Process 1 case1 window: 304 done...:chr1:171879905-172378553
    Process 1 case1 window: 305 done...:chr1:172379981-172878619
    Process 1 case1 window: 306 done...:chr1:172887107-173386849
    Process 1 case1 window: 307 done...:chr1:173389737-173885153
    Process 1 case1 window: 308 done...:chr1:173897461-174397975
    Process 1 case1 window: 309 done...:chr1:174402208-174898978
    Process 1 case1 window: 310 done...:chr1:174902955-175403361
    Process 1 case1 window: 311 done...:chr1:175404592-175904423
    Process 1 case1 window: 312 done...:chr1:175905268-176406304
    Process 1 case1 window: 313 done...:chr1:176408749-176909132
    Process 1 case1 window: 314 done...:chr1:176921556-177416698
    Process 1 case1 window: 315 done...:chr1:177424449-177920812
    Process 1 case1 window: 316 done...:chr1:177930985-178431907
    Process 1 case1 window: 317 done...:chr1:178432917-178934788
    Process 1 case1 window: 318 done...:chr1:178936115-179438069
    Process 1 case1 window: 319 done...:chr1:179437160-179938557
    Process 1 case1 window: 320 done...:chr1:179937771-180436415
    Process 1 case1 window: 321 done...:chr1:180438589-180935755
    Process 1 case1 window: 322 done...:chr1:180939667-181440333
    Process 1 case1 window: 323 done...:chr1:181439983-181939336
    Process 1 case1 window: 324 done...:chr1:181942667-182444007
    Process 1 case1 window: 325 done...:chr1:182442778-182944453
    Process 1 case1 window: 326 done...:chr1:182943121-183443170
    Process 1 case1 window: 327 done...:chr1:183446027-183944436
    Process 1 case1 window: 328 done...:chr1:183946030-184447851
    Process 1 case1 window: 329 done...:chr1:184448051-184949122
    Process 1 case1 window: 330 done...:chr1:184948360-185447769
    Process 1 case1 window: 331 done...:chr1:185453490-185945162
    Process 1 case1 window: 332 done...:chr1:185953769-186455168
    Process 1 case1 window: 333 done...:chr1:186454797-186956734
    Process 1 case1 window: 334 done...:chr1:186954900-187453757
    Process 1 case1 window: 335 done...:chr1:187456955-187956627
    Process 1 case1 window: 336 done...:chr1:187962076-188455997
    Process 1 case1 window: 337 done...:chr1:188463401-188951998
    Process 1 case1 window: 338 done...:chr1:188965123-189466363
    Process 1 case1 window: 339 done...:chr1:189465369-189966294
    Process 1 case1 window: 340 done...:chr1:189966446-190467139
    Process 1 case1 window: 341 done...:chr1:190467863-190967696
    Process 1 case1 window: 342 done...:chr1:190969564-191463345
    Process 1 case1 window: 343 done...:chr1:191473072-191969747
    Process 1 case1 window: 344 done...:chr1:191973382-192473496
    Process 1 case1 window: 345 done...:chr1:192473745-192974601
    Process 1 case1 window: 346 done...:chr1:192974527-193475989
    Process 1 case1 window: 347 done...:chr1:193483188-193982724
    Process 1 case1 window: 348 done...:chr1:193984143-194484291
    Process 1 case1 window: 349 done...:chr1:194484958-194982466
    Process 1 case1 window: 350 done...:chr1:194985562-195487076
    Process 1 case1 window: 351 done...:chr1:195495817-195995491
    Process 1 case1 window: 352 done...:chr1:196005910-196504167
    Process 1 case1 window: 353 done...:chr1:196507189-197009006
    Process 1 case1 window: 354 done...:chr1:197008097-197508149
    Process 1 case1 window: 355 done...:chr1:197508626-198007425
    Process 1 case1 window: 356 done...:chr1:198010621-198510288
    Process 1 case1 window: 357 done...:chr1:198512161-199012822
    Process 1 case1 window: 358 done...:chr1:199017987-199511942
    Process 1 case1 window: 359 done...:chr1:199521409-200022395
    Process 1 case1 window: 360 done...:chr1:200022509-200524274
    Process 1 case1 window: 361 done...:chr1:200522583-201021808
    Process 1 case1 window: 362 done...:chr1:201025282-201524912
    Process 1 case1 window: 363 done...:chr1:201525336-202027167
    Process 1 case1 window: 364 done...:chr1:202025614-202527049
    Process 1 case1 window: 365 done...:chr1:202527724-203029640
    Process 1 case1 window: 366 done...:chr1:203030052-203529067
    Process 1 case1 window: 367 done...:chr1:203531786-204033666
    Process 1 case1 window: 368 done...:chr1:204032364-204532833
    Process 1 case1 window: 369 done...:chr1:204532782-205032840
    Process 1 case1 window: 370 done...:chr1:205034345-205533937
    Process 1 case1 window: 371 done...:chr1:205534865-206030125
    Process 1 case1 window: 372 done...:chr1:206035555-206536743
    Process 1 case1 window: 373 done...:chr1:206542221-207044019
    Process 1 case1 window: 374 done...:chr1:207044597-207544613
    Process 1 case1 window: 375 done...:chr1:207544757-208046557
    Process 1 case1 window: 376 done...:chr1:208045546-208546686
    Process 1 case1 window: 377 done...:chr1:208561543-209062464
    Process 1 case1 window: 378 done...:chr1:209063595-209565589
    Process 1 case1 window: 379 done...:chr1:209567506-210066541
    Process 1 case1 window: 380 done...:chr1:210069910-210570373
    Process 1 case1 window: 381 done...:chr1:210576073-211075299
    Process 1 case1 window: 382 done...:chr1:211076941-211572948
    Process 1 case1 window: 383 done...:chr1:211581690-212079025
    Process 1 case1 window: 384 done...:chr1:212083206-212581327
    Process 1 case1 window: 385 done...:chr1:212584793-213085166
    Process 1 case1 window: 386 done...:chr1:213084921-213584820
    Process 1 case1 window: 387 done...:chr1:213587102-214085601
    Process 1 case1 window: 388 done...:chr1:214087371-214585474
    Process 1 case1 window: 389 done...:chr1:214588746-215089575
    Process 1 case1 window: 390 done...:chr1:215088825-215588133
    Process 1 case1 window: 391 done...:chr1:215590266-216091431
    Process 1 case1 window: 392 done...:chr1:216091970-216593503
    Process 1 case1 window: 393 done...:chr1:216592741-217094466
    Process 1 case1 window: 394 done...:chr1:217092783-217592310
    Process 1 case1 window: 395 done...:chr1:217594507-218093742
    Process 1 case1 window: 396 done...:chr1:218101586-218603409
    Process 1 case1 window: 397 done...:chr1:218602159-219101473
    Process 1 case1 window: 398 done...:chr1:219105272-219605242
    Process 1 case1 window: 399 done...:chr1:219606738-220107630
    Process 1 case1 window: 400 done...:chr1:220107065-220606481
    Process 1 case1 window: 401 done...:chr1:220611921-221113483
    Process 1 case1 window: 402 done...:chr1:221114572-221616265
    Process 1 case1 window: 403 done...:chr1:221618136-222119442
    Process 1 case1 window: 404 done...:chr1:222119737-222609427
    Process 1 case1 window: 405 done...:chr1:222620813-223120978
    Process 1 case1 window: 406 done...:chr1:223123447-223624998
    Process 1 case1 window: 407 done...:chr1:223623713-224124442
    Process 1 case1 window: 408 done...:chr1:224124113-224617327
    Process 1 case1 window: 409 done...:chr1:224624396-225124776
    Process 1 case1 window: 410 done...:chr1:225129815-225631237
    Process 1 case1 window: 411 done...:chr1:225630409-226131469
    Process 1 case1 window: 412 done...:chr1:226130631-226631763
    Process 1 case1 window: 413 done...:chr1:226631517-227131287
    Process 1 case1 window: 414 done...:chr1:227132973-227630944
    Process 1 case1 window: 415 done...:chr1:227633646-228131659
    Process 1 case1 window: 416 done...:chr1:228136776-228636808
    Process 1 case1 window: 417 done...:chr1:228636822-229137062
    Process 1 case1 window: 418 done...:chr1:229139152-229640336
    Process 1 case1 window: 419 done...:chr1:229640009-230139524
    Process 1 case1 window: 420 done...:chr1:230140788-230641922
    Process 1 case1 window: 421 done...:chr1:230644233-231145942
    Process 1 case1 window: 422 done...:chr1:231151931-231647058
    Process 1 case1 window: 423 done...:chr1:231652573-232151525
    Process 1 case1 window: 424 done...:chr1:232154726-232655334
    Process 1 case1 window: 425 done...:chr1:232655016-233156067
    Process 1 case1 window: 426 done...:chr1:233155918-233656904
    Process 1 case1 window: 427 done...:chr1:233656714-234156782
    Process 1 case1 window: 428 done...:chr1:234158551-234657700
    Process 1 case1 window: 429 done...:chr1:234662469-235163989
    Process 1 case1 window: 430 done...:chr1:235164830-235666612
    Process 1 case1 window: 431 done...:chr1:235665225-236165886
    Process 1 case1 window: 432 done...:chr1:236165493-236666618
    Process 1 case1 window: 433 done...:chr1:236666948-237168708
    Process 1 case1 window: 434 done...:chr1:237168288-237669539
    Process 1 case1 window: 435 done...:chr1:237670502-238170824
    Process 1 case1 window: 436 done...:chr1:238175033-238672897
    Process 1 case1 window: 437 done...:chr1:238679909-239181886
    Process 1 case1 window: 438 done...:chr1:239180794-239681831
    Process 1 case1 window: 439 done...:chr1:239681637-240181957
    Process 1 case1 window: 440 done...:chr1:240181919-240683547
    Process 1 case1 window: 441 done...:chr1:240682011-241183944
    Process 1 case1 window: 442 done...:chr1:241185510-241684864
    Process 1 case1 window: 443 done...:chr1:241686304-242187183
    Process 1 case1 window: 444 done...:chr1:242187004-242686012
    Process 1 case1 window: 445 done...:chr1:242687791-243185363
    Process 1 case1 window: 446 done...:chr1:243188556-243690482
    Process 1 case1 window: 447 done...:chr1:243688635-244187079
    Process 1 case1 window: 448 done...:chr1:244189949-244691708
    Process 1 case1 window: 449 done...:chr1:244692435-245192059
    Process 1 case1 window: 450 done...:chr1:245193399-245691740
    Process 1 case1 window: 451 done...:chr1:245698494-246197994
    Process 1 case1 window: 452 done...:chr1:246201013-246702950
    Process 1 case1 window: 453 done...:chr1:246701292-247198791
    Process 1 case1 window: 454 done...:chr1:247204109-247702651
    Process 1 case1 window: 455 done...:chr1:247709523-248211002
    Process 1 case1 window: 456 done...:chr1:248210525-248711015
    Process 1 case1 window: 457 done...:chr1:248713388-248944637
Program aborted: 
Same reference genome file should be used in both 'scan' and msi/pro/baseline steps!!!

**Comment by PengJia6** [comment]
@Zho-o-o-u  Please make sure to align you fastq to the same reference file that you used for _scan msi_ or _pro_.

**Comment by Zho-o-o-u** [comment]
@PengJia6 Thanks for reply.  Which version of reference file that used in demo/data/data4baseline/bamForTumorOnlyBaseLine？ I want to test a pipeline by using demo normal bam files. Really thanks a lot !

**Comment by lancermiss** [comment]
应该还是-i /data/data4baseline/baseline.bam.configure4docker 这条的问题，配置文件没读好。
key command：
-i   <string>   configure files for building baseline (text file) 
        e.g.
          case1	/path/to/case1_sorted.bam
          case2	/path/to/case1_sorted.bam
          case2	/path/to/case1-sorted.bam
@PengJia6 请问下，这里为什么是配置文件为什么是text 格式的？“case1_normal_sorted.bam” -i的时候总是显示打不开bam，Open bam file failed(……), please provide valid bam file with its index file !

**Comment by PengJia6** [comment]
@lancermiss 很抱歉这么晚回复！ 这里的配置文件可以一次输入多个样本的信息，就是两列的表格，bam文件的路径尽量写为绝对路径。
  如果是在用docker版本，请注意将自己pc的路径与 docker中的路径进行映射 （使用 docker run -v 参数） 否则可能会找不到bam文件的路径。另外 本项目中的demo在ubuntu18.04系统中测试没有问题！ 
如果依然无法解决，请留下邮件，我联系您解决！如果解决了请close 这个 issue。 谢谢！
