### ISSUE TITLE
exclude secondary alignment and have mapq cutoff

### ISSUE THREAD

**Issue by ruolin** [xjtu-omics/msisensor-pro#26]
Hi, it would be nice to exclude secondary alignment by default. Thanks.

**Comment by PengJia6** [comment]
@ruolin  I think so, but do you have any supporting evidence?  And what about the supplementary alignment? Thanks!

**Comment by ruolin** [comment]
Thanks for the quick response. I know user can filter the bam first. But it is an extra step. It is good to exclude supplementary too. Those reads are inflating the counts. For example, you can take a look at region chr1:44,227,913-44,227,953 on HG19. I used NA12878. Although it is our in-house data, any public NA12878 would prove my point too, I assume.

**Comment by PengJia6** [comment]
@ruolin Thanks for your suggestions, I will check it and update in next release!

**Comment by ruolin** [comment]
Thanks!
