### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by iichelhadi** [xjtu-omics/msisensor-pro#28]
Hi all,
I am trying to run msisensor-pro scan to get a list of msi sites but keep getting "Segmentation fault (core dumped)" error.
I running this on a HPC cluster with 40gb of RAM so I don't think it should be a memory issue.
hope to get somehelp.

regards

**Comment by PengJia6** [comment]
Hi, 

@iichelhadi  Which version of msisensor-pro did you use and how did you install msisensor-pro?

best,
Peng

**Comment by iichelhadi** [comment]
> Hi,
> 
> @iichelhadi Which version of msisensor-pro did you use and how did you install msisensor-pro?
> 
> best,
> Peng

thanks for the reply.
I installed version 1.0.2 and I installed it using conda 
`conda install msisensor-pro`

**Comment by PengJia6** [comment]
There were also similar error before version 1.2.0 ([#16](https://github.com/xjtu-omics/msisensor-pro/issues/16)). Could you please try the lastet version(1.2.0). 

PS: Maybe, you need to install the 1.2.0 by docker or build by yourself. And you can also try to run the binary file, if you use ubuntu system.

**Comment by iichelhadi** [comment]
> There were also similar error before version 1.2.0 ([#16](https://github.com/xjtu-omics/msisensor-pro/issues/16)). Could you please try the lastet version(1.2.0).
> 
> PS: Maybe, you need to install the 1.2.0 by docker or build by yourself. And you can also try to run the binary file, if you use ubuntu system.

I don't have admin privileges on the HPC so I can only install the version that is available in anaconda

**Comment by PengJia6** [comment]
@iichelhadi  Could you please use the binary version? You can download it directly from [here](https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro).

**Comment by iichelhadi** [comment]
> @iichelhadi Could you please use the binary version? You can download it directly from [here](https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro).

thnk you. Not sure how to use it

**Comment by PengJia6** [comment]
@iichelhadi 

Please run the following commads! 

```
wget https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro    
chmod +x msisensor-pro     
./msisensor-pro
```

**Comment by iichelhadi** [comment]
> @iichelhadi
> 
> Please run the following commads!
> 
> ```
> wget https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro    
> chmod +x msisensor-pro     
> ./msisensor-pro
> ```

thank you for the quick response. unfortunate

**Comment by PengJia6** [comment]
@iichelhadi   

Is that all right?

**Comment by iichelhadi** [comment]
> @iichelhadi
> 
> Is that all right?

apologies. having an issue with a different library when I try to run it I get the following error:
./msisensor-pro: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory

i have contacted our IT department to resolve this issue.

**Comment by PengJia6** [comment]
@iichelhadi  Sorry for the bad installation, I have pull a request in bioconda to support msisensor-pro:v1.2.0 installation with conda.  Please install msisensor-pro with 
```
conda install msisensor-pro 
```

**Comment by iichelhadi** [comment]
> @iichelhadi Sorry for the bad installation, I have pull a request in bioconda to support msisensor-pro:v1.2.0 installation with conda. Please install msisensor-pro with
> 
> ```
> conda install msisensor-pro 
> ```

I did as you mentioned. The version installed is v1.0.2 instead of v1.2.0

**Comment by PengJia6** [comment]
@iichelhadi  Thanks for your patient!
