### ISSUE TITLE
Where to download baseline microsatellites information file?

### ISSUE THREAD

**Issue by Nana7926** [xjtu-omics/msisensor-pro#29]
I notices the notes in the README file said "2. If you don't have normal samples to build baseline(baseline step for tumor only sample detection), you can download the microsatellites information with baseline on our github or use -i option in pro module to set a hard cutoff directly.". May I know the exact link to download the file? Thanks

**Comment by PengJia6** [comment]
@Nana7926  Thanks for your question! 

We have the baseline files of CRC,STAD and UCEC built by TCGA dataset. But, these baselines are just for GRCh38 aligned bam file.  And I will send you by email.

**Comment by chenzemin** [comment]
> @Nana7926 Thanks for your question!
> 
> We have the baseline files of CRC,STAD and UCEC built by TCGA dataset. But, these baselines are just for GRCh38 aligned bam file. And I will send you by email.

Could you also send me a copy?  Thank you very much.

**Comment by aaraneo21** [comment]
> @Nana7926 Thanks for your question!
> 
> We have the baseline files of CRC,STAD and UCEC built by TCGA dataset. But, these baselines are just for GRCh38 aligned bam file. And I will send you by email.

Could you please send me a copy as well? Thanks so much!

**Comment by ankurs103** [comment]
> @Nana7926 Thanks for your question!
> 
> We have the baseline files of CRC,STAD and UCEC built by TCGA dataset. But, these baselines are just for GRCh38 aligned bam file. And I will send you by email.

Can you please send me a copy/link as well?  My Email is : liver.hepato@gmail.com . Thanks in advance

**Comment by faruqsandi** [comment]
can you please send me the the baseline files ([faruqsandi@antardata.com](mailto:faruqsandi@antardata.com))? Or probably give me a clue how to build one? Thanks.

**Comment by Taoyegbio** [comment]
> @Nana7926 Thanks for your question!
> 
> We have the baseline files of CRC,STAD and UCEC built by TCGA dataset. But, these baselines are just for GRCh38 aligned bam file. And I will send you by email.

Can you please send me a copy/link as well? My Email is : qqlzt123456@163.com . Thanks so much!

**Comment by OrangePomeranian** [comment]
Can I also get the link/copy? Email: d.plewa25@gmail.com 
Thank you very much

**Comment by PengJia6** [comment]
@chenzemin @OrangePomeranian @Taoyegbio @ankurs103 @aaraneo21 @Nana7926  

Please find the baseline file here: https://github.com/xjtu-omics/msisensor-pro/tree/master/data
