### ISSUE TITLE
Is it possible to adapt this tool for running on VCF/MAF?

### ISSUE THREAD

**Issue by jjgao** [xjtu-omics/msisensor-pro#3]
For published studies, we usually don't have access to BAM. I am wondering if it is possible to calculate MSI scores just based on called mutations?

**Comment by PengJia6** [comment]
> For published studies, we usually don't have access to BAM. I am wondering if it is possible to calculate MSI scores just based on called mutations?

I am sorry, It is not available for MSI calling based on VCf/MAF in current version. Thanks for your suggestion. We will explore the prosibility of you mentioned in the future, but the key problem is that researchers may get different VCF from one same bam file, because of the different usage of softwares and parameters.

**Comment by jjgao** [comment]
@PengJia6 thanks for the response! It would be great if we will be able to use it on MAF. We are very interested in calculating msi scores for all samples in cBioPortal, but we don't have access to most of the BAM files. https://github.com/cBioPortal/datahub/issues/1043

**Comment by jjgao** [comment]
Another related question: do you happen to have msi scores for all tcga samples? If so, we would be very interested in integrating them into cBioPortal.

**Comment by PengJia6** [comment]
> Another related question: do you happen to have msi scores for all tcga samples? If so, we would be very interested in integrating them into cBioPortal.

I am sorry we do not have msi scores for all tcga samples. We just called the sample in in colorectal cancer (CRC), stomach adenocarcinoma (STAD), and uterine corpus endometrial carcinoma (UCEC) in TCGA and you can find the results in our [research paper](https://www.sciencedirect.com/science/article/pii/S1672022920300218 ).

**Comment by PengJia6** [comment]
> @PengJia6 thanks for the response! It would be great if we will be able to use it on MAF. We are very interested in calculating msi scores for all samples in cBioPortal, but we don't have access to most of the BAM files. [cBioPortal/datahub#1043](https://github.com/cBioPortal/datahub/issues/1043)

Thanks for you advance, we will do it in the future.

**Comment by jjgao** [comment]
Thanks, @PengJia6!

**Comment by PengJia6** [comment]
@jjgao Hi, we have launched new software [MSIsensor-RNA](https://github.com/xjtu-omics/msisensor-rna) for MSI detection with RNA-seq data. If you do not have access to bam files, it is a choice for you to try with RNA expression data, like FPKM.
