### ISSUE TITLE
Support cram files

### ISSUE THREAD

**Issue by kcleal** [xjtu-omics/msisensor-pro#31]
Feature request: please can you support cram files?

**Comment by PengJia6** [comment]
We support cram file in our new version, v1.2.0, please have a try. If you have any problem when you use cram as input, please feel free to contact us.

**Comment by kcleal** [comment]
Oh thanks, could you push the 1.2 release to conda?

**Comment by PengJia6** [comment]
@kcleal   I have update this 1.2 release to support conda two weeks ago, please see [here](https://anaconda.org/bioconda/msisensor-pro/files?__cf_chl_jschl_tk__=pmd_cd3c666512d01fda2fc9ec199b0eb626e5fb08ae-1627390908-0-gqNtZGzNAjijcnBszQrO). 
Now, you can install the msisensor-pro v1.2 with  

```
conda install -c bioconda msisensor-pro=v1.2.0
```

**Comment by kcleal** [comment]
Ok thanks, when I ran `conda install -c bioconda msisensor-pro` it installed 1.1. Thanks again
