### ISSUE TITLE
discriminative microsatellite site (DMS) from paper

### ISSUE THREAD

**Issue by syan1** [xjtu-omics/msisensor-pro#32]
> This module scans the reference genome to get microsatellites information. You need to input (-d) a reference file (*.fa or *.fasta), and you will get a microsatellites file (-o) for following analysis. If you use GRCh38.d1.vd1 , you can download the file on out github directly.

@PengJia6 Do you have this file somewhere in the project? I cannot seem to locate it. I assume the file referred to in the wiki is the ~7700 sites DMS from the paper? Thank you.

**Comment by PengJia6** [comment]
You can download from the supplementary information of the paper.

**Comment by syan1** [comment]
Thank you but I cannot build a microsatellite file (scan output) from that table without some more information. 

What does the "_binary" columns indicate and how should I replicate that from the sites in your supplementary table?

Thank you so much for your help!

**Comment by PengJia6** [comment]
Hi, it is binary code of the sequence.  

Here, we encode A, C, G, and T with binary number 00, 01, 10, and 11. 
If you have sequence GT, it should be code with **1011** (binary), its  decimal value is **11**.

**Comment by mital14** [comment]
how can we download msi reference list file?

**Comment by bounlu** [comment]
@mital14 I believe it's [this file](https://github.com/xjtu-omics/msisensor-pro/blob/master/data/GRCh38.baseline_TCGA.tsv).

**Comment by PengJia6** [comment]
> @mital14 I believe it's [this file](https://github.com/xjtu-omics/msisensor-pro/blob/master/data/GRCh38.baseline_TCGA.tsv).

It is!
