### ISSUE TITLE
feature request: indicate deletion or insertions

### ISSUE THREAD

**Issue by kcleal** [xjtu-omics/msisensor-pro#35]
In tumor/normal mode, how can I tell if a site is a deletion or insertion in the tumor? I can only see a `difference` column. It might be more useful to report something like `tumor content / normal content` rather than `(AreaMax - AreaMin)/AreaMax`

**Comment by PengJia6** [comment]
@kcleal do you mean tumor purity？

**Comment by kcleal** [comment]
Sorry, I mean for the sites that are identified in the somatic output file .e.g:

    chromosome	location	left_flank_bases	repeat_times	repeat_unit_bases	right_flank_bases	difference	P_value	FDR	rank

    chr3	54867528	GCTTT	14	A	GGCCT	0.92857	1.028e-06	0.027473	1 

When I look at this loci in IGV, I can see that the 'tumor' sample is homozygous for a 4bp deletion, whereas the 'normal' sample is heterozygous with a 3bp and a 4bp deletion. So the tumor has an extra 'deletion' (normal top pane, tumor bottom pane):

<img width="775" alt="Screenshot 2021-09-06 at 10 47 04" src="https://user-images.githubusercontent.com/42997789/132197878-b3b26891-c83a-40ea-86b1-c049a39e55fb.png">

An example of an 'insertion' site is

    chr13	64153219	TTTTC	13	T	GAAAA	0.84211	8.6836e-06	0.021096	11

<img width="849" alt="Screenshot 2021-09-06 at 10 54 19" src="https://user-images.githubusercontent.com/42997789/132198569-7769b4db-6e9b-4e54-8299-e34ae88bd8eb.png">

Here the 'tumor' sample has an extra 1bp added to one of the alleles. 

From the output, im not sure it is possible to distinguish deletion sites from insertion sites in the tumor. Hope that makes sense

**Comment by PengJia6** [comment]
Thanks for your clarification, MSIsensor-pro (msi command) just compare the tumor and normal sequence read in microsatellite regions and tell you if it is a somatic mutation or not and final we report the msi score. We do not report a details like deletion or insertion of microsatellite. I think you may try somatic mutation caller like mutect2.
