### ISSUE TITLE
msisensor scan segfault

### ISSUE THREAD

**Issue by b-math** [xjtu-omics/msisensor-pro#38]
Dear development team,

I wanted to test msisensor, but when starting the `msisensor scan` programm, an immediate Segmentation fault occurs.

![image](https://user-images.githubusercontent.com/79646548/136151133-11ea5843-8bd6-49e5-814f-a3d3e73cb2f5.png)

I tested the version hosted on bioconda (v 0.5) on two different PCs, and additionally built the current version (0.6) from source code on one PC. In all three cases a Segmentation fault occured immediately.

Additionally, I tested the `msisensor-pro scan` command (built from source code), giving the same result.

Do you have any suggestions, how I could circumvent this problem?

I further tested the `scan` command of msisensor2, which managed to scan the genome. The resulting file seemed to be compatible with `msisensor msi`, as it did not give any errors. Do you have any experience whether `msisensor scan` and `msisensor2  scan` give the same result or just share the same file format?

Thanks for your time 
Barbara

**Comment by PengJia6** [comment]
Hi Barbara,

msisensor-pro is the update version of msisensor and it inherits all functions of msisensor.  We only support msisensor-pro now.  I suggest you install lastet version (v1.2) of msisensor-pro by bioconda and test again. 

Best,
Peng

**Comment by b-math** [comment]
Hi Peng,

thank you very much for the fast reply. 

The update to version v1.2 resolve the problem for me. Thanks for the suggestion.

However, would it be possible to make v1.2 the default version in bioconda? Currently, v1.0.2 is set as default.

Best,
Barbara
