### ISSUE TITLE
No MSI found

### ISSUE THREAD

**Issue by davidlord** [xjtu-omics/msisensor-pro#40]
Greetings, 

I ran MSIsensor-pro on tumor-normal paired samples from oncogene panel reads, following the workflow of your best practices precisely. However, in my output no MSI is detected whatsoever. Are there any additional parameters or input flags that I should be considering?

**Comment by PengJia6** [comment]
Thank you for clarifying!  
First, please check the reference, make sure the reference your reads aligned(bam file) is the same as the one you generated msi sites (scan module). 
Second, what is your data type? WES, WGS or target sequencing panel? If your sequencing region does not cover microsatellite regions, it will also not detect any msi sites.

**Comment by zhijunyuu** [comment]
> How about the sequencing depth? could you please check the sequence depth at some msi sites using IGV?

Hi PengJia,

Thanks for the tool. I have a relevant question regarding the sequence depth. Now I have some low-pass WGS data, the sequence depth is about 10X, will this be enough for MSI detection? Thanks for your time!

Best,
Zhijun
