### ISSUE TITLE
Less than 200% cpu usage even set -b to 10

### ISSUE THREAD

**Issue by xzhub** [xjtu-omics/msisensor-pro#41]
I am using pengjia1110/msisensor-pro to analyze a pair of Tumor and Normal bam files. The command is : 
```
docker run --cpus=16 -i --rm pengjia1110/msisensor-pro msisensor-pro msi -b 10 -d ... -n .. -t .. -e .. -o .. 
```
I only observed max ~150% cpu usage, and the speed is almost the same with -b 1, if not slower.

Is this normal? or if I did anything wrong? Thanks!

**Comment by PengJia6** [comment]
Hi,

It is normal,  because not all steps are paralleled in MSIsensor-pro. 

If you have many samples, you can run multipe samples with -b1 at same time. 


Best, 
Peng

**Comment by xzhub** [comment]
Got it, thanks!
