### ISSUE TITLE
Could it run on msisensor-pro that using different type of data between the 2nd step ( build baseline ) and the 3rd step ( evaluate MSI )

### ISSUE THREAD

**Issue by bio-rain** [xjtu-omics/msisensor-pro#43]
I have some normal sample sequence data (WGS), and some tumor sequence data (WES/WXS).
I'd like to use normal data (WGS) to build baseline, then use tumor data to evaluate MSI.
Could I use these data to run msisensor-pro? 
Or the 2nd step use WES data, then 3rd step use WGS data?

Thank you for your answer😀.

**Comment by PengJia6** [comment]
Hi, Yes! you can!

**Comment by bio-rain** [comment]
Thanks!
Different results due to different baselines, I'd like to check the different results between my baseline and the baseline of msisensor-pro paper. Could you send me email for paper's baseline (I saw it mentioned in another question) or where I can download it?
Thank you for your help.
