### ISSUE TITLE
The MSI loci both in output.prefix_germline and output.prefix_somatic

### ISSUE THREAD

**Issue by litun-fkby** [xjtu-omics/msisensor-pro#45]
when use msisensor or msisensor-pro msi to  analyze the tumor-normal pair data , some MSI loci both in output.prefix_germline and output.prefix_somatic，such as:
CRC_16_germline
chr1	151196702	GATTG	9	T	CCCCC	9|9
chr1	151196711	TTTTT	6	C	TAGCA	6|6
chr1	200594041	AACAA	8	T	AAGGC	8|8
chr2	148683685	TGCAT	8	A	GAGGC	8|8
chr3	51417603	TGATA	7	C	AGCCC	7|7
chr7	55273591	ATTTG	13	A	GTATA	14|14
chr7	74608740	ACTGC	13	T	ATGGT	13|13
chr7	143003662	TTTTT	19	A	CTTCC	19|19
chr8	7346866	GTCCC	9	T	GGTGG	9|9
chr8	7679727	CCACC	9	A	GGGAC	9|9
chr11	120350636	ATATG	8	T	CCCCC	8|8
chr11	120350644	TTTTT	5	C	TCCTT	5|5
chr16	14983091	GAGTT	9	A	CCCAT	9|9
chr16	56718015	CTGGA	20	T	GTACA	19|19
chr17	56435160	AGGGA	7	C	GCCTT	7|7

CRC_16_somatic
chr17	56435160	AGGGA	7	C	GCCTT	0.67666	1e-14	2.4e-13	1
chr16	56718015	CTGGA	20	T	GTACA	0.94734	1e-14	1.2e-13	2
chr16	14983091	GAGTT	9	A	CCCAT	0.040581	1e-14	8e-14	3
chr14	23652346	TTGCT	21	A	GGCCA	0.98116	1e-14	6e-14	4
chr11	125490765	GAAGA	21	T	AATAT	0.84764	1e-14	4.8e-14	5
chr11	120350636	ATATG	8	T	CCCCC	0.031458	1e-14	4e-14	6
chr11	102193508	CTGGT	26	A	GCCAC	0.87536	1e-14	3.4286e-14	7
chr8	7679727	CCACC	9	A	GGGAC	0.74167	1e-14	3e-14	8
chr8	7346866	GTCCC	9	T	GGTGG	0.74167	1e-14	2.6667e-14	9
chr7	143003662	TTTTT	19	A	CTTCC	0.73456	1e-14	2.4e-14	10
chr7	143003342	AAGAC	25	T	GAGAC	0.95439	1e-14	2.1818e-14	11
chr7	74608740	ACTGC	13	T	ATGGT	0.8415	1e-14	2e-14	12
chr7	55273591	ATTTG	13	A	GTATA	0.97535	1e-14	1.8462e-14	13
chr4	55598211	TTTGA	25	T	GAGAA	0.98916	1e-14	1.7143e-14	14
chr3	51417603	TGATA	7	C	AGCCC	0.71456	1e-14	1.6e-14	15
chr2	148683685	TGCAT	8	A	GAGGC	0.99445	1e-14	1.5e-14	16
chr2	95849361	TCCTA	23	T	GTGAG	0.87912	1e-14	1.4118e-14	17
chr2	47641559	CAGGT	27	A	GGGTT	0.99225	1e-14	1.3333e-14	18
chr2	39564893	TCCAG	28	T	GAGAC	0.90117	1e-14	1.2632e-14	19
chr2	39536689	CAGGA	27	T	GAGGC	0.88219	1e-14	1.2e-14	20
chr1	200594041	AACAA	8	T	AAGGC	0.99484	1e-14	1.1429e-14	21
chr1	151196702	GATTG	9	T	CCCCC	0.67961	1e-14	1.0909e-14	22
chr1	151196711	TTTTT	6	C	TAGCA	0.0095938	3.0295e-05	3.1612e-05	23

but the output.prefix :
Total_Number_of_Sites	Number_of_Somatic_Sites	%
24	23	95.83

the msi loci in output.prefix_germline means the  stable loci? if that,the msi result will be:
Total_Number_of_Sites	Number_of_Somatic_Sites	%
24	(23-15)	33.33

I'm very confused about this,  and hope your  reply!

**Comment by PengJia6** [comment]
I think the output.prefix_germline contained msi sites that had germline mutations, while the output.prefix_somatic included the msi sites that had somatic mutations. 
Total_Number_of_Sites refers to the total number of sites that passed quality control!

**Comment by litun-fkby** [comment]
one same msi site can be both germline mutation and somatic mutation?
