### ISSUE TITLE
How to use custom MS file

### ISSUE THREAD

**Issue by rained1989** [xjtu-omics/msisensor-pro#5]
Hi,

Could you kindly tell me how to use custom MS file to run msisensor-pro?

Thanks very much,

Kimdo

**Comment by PengJia6** [comment]
Hi, please see the [Best Practice](https://github.com/xjtu-omics/msisensor-pro/wiki/Best-Practices#best-practices-for-msi-classification-using-msisensor-pro) in [Wiki](https://github.com/xjtu-omics/msisensor-pro/wiki).
