### ISSUE TITLE
How to determine low and high cut-offs?

### ISSUE THREAD

**Issue by komalsrathi** [xjtu-omics/msisensor-pro#50]
Hi,

Here is the distribution of the % Somatic sites from 132 paired tumor-normal msisensor runs (WGS):

![image](https://user-images.githubusercontent.com/7000615/192801057-928c200f-8264-49a6-b51b-6d3a9cf0d538.png)

Is there a cut-off that can tell me what is considered as low or high instability?

Thanks!

**Comment by PengJia6** [comment]
Did you use whole exom sequencing techonology or target gene sequencing? I think 2% is this best cut-off  for your solutions!

**Comment by PengJia6** [comment]
> Based on our runs, I have checked it says `Whole Genome Sequencing`.

For whole exome sequencing, the cut-off may be 3.5%, you could found it in msisensor [paper](https://www.ncbi.nlm.nih.gov/pubmed/24371154). For WGS, I suggest you validate two samples with MSI-PCR (gold standard) if you have materials.

**Comment by komalsrathi** [comment]
Thank you very much for the feedback.
