### ISSUE TITLE
Scan output

### ISSUE THREAD

**Issue by yazbeck** [xjtu-omics/msisensor-pro#53]
Hi,
Is the **.list** output of the scan command, is zero or 1 -based?

"msisensor-pro scan -d /path/to/reference.fa -o /path/to/**reference.list**"

Thanks

**Comment by yazbeck** [comment]
As per the developer, the output file is 0-based.

**Comment by ankurs103** [comment]
Hi I used this command: sudo docker run pengjia1110/msisensor-pro msisensor-pro scan -d /home/ubuntu/msi_pro/Homo_sapiens_assembly38.fasta -o /home/ubuntu/msi_pro/reference.list 

I got this error: fatal error: failed to open ref file
scan -d /home/ubuntu/msi_pro/Homo_sapiens_assembly38.fasta -o /home/ubuntu/msi_pro/reference.list Start at:  Mon Jul 10 08:30:11 2023
