### ISSUE TITLE
Baseline step for tumor-only pipeline

### ISSUE THREAD

**Issue by komalsrathi** [xjtu-omics/msisensor-pro#55]
Hi,

We have 91 cram files that we need to run through the tumor-only pipeline. Should we run the baseline step with all the 91 files or randomly take a subset? Please let me know.

Thanks!

**Comment by PengJia6** [comment]
I think maybe you could use all of these files.

**Comment by ankurs103** [comment]
Do we need normal bams for baseline step? If yes, can you please share normal bams ?
