### ISSUE TITLE
How to determine the exact number of repetition of a MSI site in tumor samples

### ISSUE THREAD

**Issue by Giuseppe1995** [xjtu-omics/msisensor-pro#56]
Hi,
First of all, thank you for your tool!
As the title of this issue suggests, I would like to know whether is possible to determine the exact number of repeating units for each site of MSI in the tumor after a matched tumor-normal MSI calling. I'll explain better:
I performed msi-sensor analysis on a matched tumor-normal sample, so let SAMPLE indicate it. After the calling, I have a file, named `SAMPLE_somatic`, and here's an `head` of it

> chromosome	location	left_flank_bases	repeat_times	repeat_unit_bases	right_flank_bases	difference	P_value	FDR	rank
> 2	16242333	CCGGC	5	GT	ACGAA	0.69986	2.6939e-152	4.4125e-146	1
> 1	188314049	CCCAC	5	AT	GTGTG	0.65582	4.273e-53	3.4995e-47	2
> 1	185347694	TATTT	9	TTTTA	TTATT	0.61092	2.3495e-49	1.2828e-43	3
> 1	78733453	ATCTC	6	CCCT	TCCTT	0.71136	2.8898e-35	1.1833e-29	4
> 1	188153379	AATAA	11	AAAT	GGGAC	0.73154	1.5622e-25	5.1174e-20	5
> 2	16145619	GGTTA	10	T	CCTTT	0.48005	1.4833e-23	4.0491e-18	6
> 1	78619969	TTTTC	16	T	GAGAT	0.5053	1e-14	2.3399e-09	7
> 1	78599434	AAAAT	19	TG	TATGT	0.68689	1e-14	2.0474e-09	8
> 1	78641345	GTCTC	28	A	GAAGA	0.7225	1e-14	1.8199e-09	9
> 

Now, for the firs site (as an example), I have that the number of repeating units is 5, but is five in the reference, as I can see by running:
`grep '^2' reference.msiFile | grep -w '16242333'`

> 2	16242333	2	11	5	361	96	GT	CCGGC	ACGAA

And as was confirmed by IGV analysis. So, if this site has been called as MSI, I would like to know if there's a way do detect the exact number of repeating unit in the tumor for this site.

Thank you in advance, 
Giuseppe

**Comment by ZooJooFoo** [comment]
check the *_dis file
chr1 1090291 CTGGG 5[CA] CCAGT
N: 0 0 0 2 72 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
T: 0 0 0 11 26 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
normal repeats：5

**Comment by Giuseppe1995** [comment]
this is the SAMPLE_dis at the '2 16242333' site:

> 2 16242333 CCGGC 5[GT] ACGAA
> N: 0 0 0 0 24 30 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
> T: 0 0 0 1 49 2980 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
> 

Honestly, I don't have a clue about how to interpret it!

**Comment by Giuseppe1995** [comment]
Perfect, I got it now. Thank you very much for the explanation!

**Comment by fangling0913** [comment]
Hi, I would like to ask a related question. Are these "No. of supporting reads" referring to before or after deduplication?
