### ISSUE TITLE
Having issue at Assert(idx) for msi tumor/normal

### ISSUE THREAD

**Issue by shivUSF** [xjtu-omics/msisensor-pro#57]
Hello, 
I am using msisensor-pro msi command for tumor/normal paired sample [command mentioned below] However i am again and again running in this error. 
Initially I thought there is some sort of path error but the paths seems file for tumor normal bam files. 
Does it need any other file along with the bam file? 

Error -----
loading bed regions ...
loading homopolymer and microsatellite sites ...

Total loading windows:  2893

Total loading homopolymer and microsatellites:  18252

" [E::idx_find_and_load] Could not retrieve index file for '/mnt/cancergenomics/CCB/gastric_rna_ikl/variant_dna/220300000233-D01/alignment/220300000233-D01_realigned.bam'
msisensor-pro: bamreader.cpp:187: bool ReadInBamReads(const char*, const string&, unsigned int, unsigned int, std::vector<SPLIT_READ>&, std::string): Assertion `idx' failed. "
msisenssor2.sh: line 4: 1266786 Aborted               
  (core dumped) msisensor-pro msi -d /mnt/cancergenomics/aws_ebs/ikmb_gastric/b37decoy.miscrosatellites.list -t /mnt/cancergenomics/CCB/gastric_rna_ikl/variant_dna/220300000233-D01/alignment/220300000233-D01_realigned.bam -n /mnt/cancergenomics/CCB/gastric_rna_ikl/variant_dna/220300000233-D01/alignment/220300000233-F01_realigned_sorted.bam -e /mnt/cancergenomics/aws_ebs/database/avera/xgen_exome_nochr_6_sorted.bed -o /mnt/cancergenomics/CCB/gastric_rna_ikl/variant_dna/220300000233-D01/report/220300000233-D01.msi

------------------------------------

**Comment by PengJia6** [comment]
Did you have bam index file along with you bam file?  If not, please generated with following scripts: 

```
samtools index xxxx.bam
```
