### ISSUE TITLE
大批量肿瘤样品分析策略

### ISSUE THREAD

**Issue by wangshun1121** [xjtu-omics/msisensor-pro#6]
大批量无Normal肿瘤样品，如何创建baseline？目前手上有从SRA上搜罗的接近600例肿瘤RNA seq数据，目前尝试同时跑着批数据构建baseline，但尝试两次均失败了，detail中留下大约60样品的运行记录，然后得到一个空白的baseline。

那么，msisensor-pro可否分批次构建baseline，然后再合并呢？希望给点意见。

**Comment by PengJia6** [comment]
请提供一下报错提示，另外MSIsensor-Pro在RNA-Seq数据中的性能没有测试，请谨慎使用！

**Comment by PengJia6** [comment]
@wangshun1121  您好！ 我们最近开发了基于RNA测序的微卫星不稳定性检测算法[MSIsensor-RNA](https://github.com/xjtu-omics/msisensor-rna) ， 欢迎使用测试，并提出宝贵意见！
