### ISSUE TITLE
Baseline for tumor only

### ISSUE THREAD

**Issue by da-otero** [xjtu-omics/msisensor-pro#60]
Hello.

I read you recommend at least 20 samples to make the baseline. However I don´t have that many.

Can you send me the baselines file are for GRCh38 that you mention in another posts?

Thx

**Comment by ankurs103** [comment]
Hello, I am also looking for normal samples to make baseline. Is it available online ?

**Comment by PengJia6** [comment]
@ankurs103 @da-otero   Please download the file you need from the link below.

https://github.com/xjtu-omics/msisensor-pro/blob/master/data/GRCh38.baseline_TCGA.tsv

**Comment by ankurs103** [comment]
That's not the baseline configuration file I think. That looks more like "microsatellite file". 
The baseline file looks like this for me (trail with 3 normal samples first) but I am getting the error "Open configure file failed, please provide valid configure file !"

My script is: sudo docker run pengjia1110/msisensor-pro msisensor-pro baseline -d reference.list -i baseline.bam.configure -o .

NA12878_A9      /data/NA12878_A9.recal.bam
NA12878V500     /data/NA12878V500.recal.bam
NA12878_B2      /data/NA12878_B2.recal.bam

**Comment by PengJia6** [comment]
@ankurs103   I think you may need to use -v option （docker run ） to mapping your local path to the docker environment path.

**Comment by ankurs103** [comment]
Hi Dr Peng Jia,
Thanks a lot for your response.
I am just curious to know how do you interpret the results?
 Let's say the the result is (as shown below), will this be MSI-H or low?
What is the criteria for MSI sensor pro %?


[image: image.png]

Best regards,
Ankut

*ANKUR B. SHARMA*
Contact Details:+65-84026093
***@***.***
***@***.***
