### ISSUE TITLE
issues on toy dataset

### ISSUE THREAD

**Issue by nservant** [xjtu-omics/msisensor-pro#61]
Hi,
When running MSIsensor-pro on a very small data for unit testing, the tool crashes saying ;

```
loading bed regions ...
loading homopolymer and microsatellite sites ...

Total loading windows:  1 


Total loading homopolymer and microsatellites:  0 

Program aborted: 
Same reference genome file should be used in both scan and msi/pro/baseline steps!!!
```

I'm almost sure the error is not linked to the reference genome, as `scan` and `msi` has been run with the same input file.
My feeling is that this error is raised because the toy dataset is too small, and that no homopolymer/microsatellites are detected. Would it make sense ?
Thanks

**Comment by PengJia6** [comment]
@nservant  I think this error is not related to the size of the dataset. Can you check your MSI sites file to make sure that the first column of each row can be found in the header of the BAM file? You can also share your input files so that we can reproduce this error.

**Comment by nservant** [comment]
Sorry for being so long ... that's the reverse actually, as this is a small data, the BAM file contains more chromosome in his header than the MSI site file.
I guess all chromosomes do not have a read mapped.
Does it explain the issue ?

**Comment by PengJia6** [comment]
I apologize for the delayed response. If you are still using it, please check version 1.3.0; this issue should have been resolved.
