### ISSUE TITLE
the place to put .bam.bai

### ISSUE THREAD

**Issue by Elizabeth237** [xjtu-omics/msisensor-pro#63]
Hi，

We have a place to store our bam, but this place cannot store .bam.bai. I made a bam link to another place and made a .bam.bai. My question is how to solve the problem that the original bam and bai are placed in different folders.
It looks like this:
/path/A.bam -> /usr/bin/A.bam
/path/A.bam.bai
 
![image](https://github.com/xjtu-omics/msisensor-pro/assets/44385901/6f8ea80f-a05c-454f-8c32-0c746b82e283)

Thank you!

**Comment by Elizabeth237** [comment]
I commented out these two lines，then it is OK
distribution.cpp: line 75 and 76
![image](https://github.com/xjtu-omics/msisensor-pro/assets/44385901/d4252dce-445a-40e4-a095-ab8c4d053912)

**Comment by PengJia6** [comment]
Thank you for reporting this issue!
