### ISSUE TITLE
Parallelization of samples for baseline

### ISSUE THREAD

**Issue by bounlu** [xjtu-omics/msisensor-pro#64]
I want to create a baseline from 58 normal samples. I specified them in the config file and it runs fine with `msisensor-pro baseline` command.

However, even though I specified the number of threads high enough (`-b 64`), it still goes sequentially through the samples one by one, chrom by chrom and region by region. Each sample takes about 1 hour to finish totaling to about 58 hours in my case. Is there a way to efficiently parallelize this?

I can use GNU parallel to run 58 samples simultaneously, but then how can I merge the results into 1 reference file?

**Comment by lichennan123** [comment]
Same question here. Have you figured out your solution yet? @bounlu

**Comment by bounlu** [comment]
@lichennan123

No

**Comment by PengJia6** [comment]
Version 1.3.0 provides a faster pipeline for [establishing the baseline](https://github.com/xjtu-omics/msisensor-pro/blob/master/snakemake/tumor_only/tumor_only.smk), which is based on Snakemake.
