### ISSUE TITLE
Does the msi site for a target panel need to be filtered?

### ISSUE THREAD

**Issue by h170607** [xjtu-omics/msisensor-pro#67]
Hi
We analyzed the msi of a set of tumor-normal paired samples. The results are all above 40%,  which are suspicious from experience. We used scan and msi steps.
We wonder if the reference.site need to be filtered with the capture region of the panel.
We noticed that the capture region was not used throughout the pipeline.

**Comment by PengJia6** [comment]
You can manually modify the file generated by the scan and remove the loci that are not in the target region.
