### ISSUE TITLE
failed to open file: /local/scrath/test/homo.list

### ISSUE THREAD

**Issue by songeric1107** [xjtu-omics/msisensor-pro#68]
try to run as following

msisensor-pro scan -d /local/db-build/gatk/hg38/Homo_sapiens_assembly38.fasta -o /local/scrath/test/homo.list

always get errors as following

failed to open file: /local/scrath/test/homo.list

**Comment by PengJia6** [comment]
I believe this is related to the permissions of your system. The directory specified by the -o parameter must be writable, and the parent directory must already be created.
