### ISSUE TITLE
Inverting tumour and saliva BAMs in tumor-normal paired gives the same results

### ISSUE THREAD

**Issue by timothee-revil** [xjtu-omics/msisensor-pro#7]
Hi,

As a quick check for the calls obtained, I ran the analysis in reverse, that is using the tumour as a normal sample, and the normal sample as a tumour. Strangely, this gives exactly the same results as a normal analysis.

Is this expected?

Thanks,
Tim

**Comment by PengJia6** [comment]
> Hi,
> 
> As a quick check for the calls obtained, I ran the analysis in reverse, that is using the tumour as a normal sample, and the normal sample as a tumour. Strangely, this gives exactly the same results as a normal analysis.
> 
> Is this expected?
> 
> Thanks,
> Tim
Hi  Tim,

Thanks for your test! I guess you use **msi** command. If that, this is expected. **msi** command in msisensor-pro is same with that in [msisensor](https://github.com/ding-lab/msisensor) . **msi** command just capture the instability singal by comparing the microsatetllite difference between tumor and normal sample using chi-square test.  Did I answer your question?

**Comment by PengJia6** [comment]
> Hi,
> 
> As a quick check for the calls obtained, I ran the analysis in reverse, that is using the tumour as a normal sample, and the normal sample as a tumour. Strangely, this gives exactly the same results as a normal analysis.
> 
> Is this expected?
> 
> Thanks,
> Tim


Hi Tim,

Thanks for your test! I guess you use **msi** command. If that, this is expected. **msi** command in msisensor-pro is same with that in [msisensor](https://github.com/ding-lab/msisensor). **msi** command just capture the instability singal by comparing the microsatetllite difference between tumor and normal sample using chi-square test. Did I answer your question?

Best, 
Peng

**Comment by timothee-revil** [comment]
Yes, this answers my question perfectly. This is a bit what I had guessed.

Thanks again for this tool, works great for what I'm doing!

Tim
