### ISSUE TITLE
seline files for cancer samples only

### ISSUE THREAD

**Issue by 20221122** [xjtu-omics/msisensor-pro#71]
Hello, I have a total of more than 100 files on cancer, but there is absolutely no corresponding normal samples to use as a control, I see that I can use the baseline files provided by github, but I am facing a problem that the reference I am using is human_g1k_v37_decoy.fa. what is the solution for this situation please? Can I use all the files to create the baseline first and then analyse all the files later?

**Comment by PengJia6** [comment]
Switching the reference genome to GRCh38 is an option, but I believe it would be inconvenient for you. We are now working on developing a baseline-independent MSI detection method, but the software has not been officially released yet. If you would like to test it, you can contact me at pengjia@xjtu.edu.cn.
