### ISSUE TITLE
Output MSIsensor-pro (unstable, dis and all)

### ISSUE THREAD

**Issue by OrangePomeranian** [xjtu-omics/msisensor-pro#72]
I haven't found on the Wiki more detailed information regarding the output files (unstable, dis and all). Could you explain a bit more about the columns contained in them here? Thank you very much.

**Comment by PengJia6** [comment]
Please see the detail [here](https://github.com/xjtu-omics/msisensor-pro/blob/master/docs/5_files_type.md).
