### ISSUE TITLE
failed to open output files to write !

### ISSUE THREAD

**Issue by Bang9suK** [xjtu-omics/msisensor-pro#73]
Running the msi module returns the following:

`hwanho@linux:/mnt/bigHDD/resource/ref_and_tools/tools/msisensor-pro$ ./binary/msisensor-pro msi -d ./Homo_sapiens.GRCh38.dna.primary_assembly.msi.list -n ./test/460NT-D__GRCh38_aligned.bam -t ./test/460TT-D__GRCh38_aligned.bam -o ./test/
msi -d ./Homo_sapiens.GRCh38.dna.primary_assembly.msi.list -n ./test/460NT-D__GRCh38_aligned.bam -t ./test/460TT-D__GRCh38_aligned.bam -o ./test/ Start at:  Tue Jun 11 15:34:56 2024

loading homopolymer and microsatellite sites ...

Total loading windows:  5895

Total loading homopolymer and microsatellites:  1800173

failed to open output files to write !`

This happens even when I run the command with sudo or as root user.

OS is Ubuntu 18.04 LTS

**Comment by PengJia6** [comment]
@Bang9suK  Please try to set the -o option without ending it with "/".

**Comment by agnes-csw** [comment]
Hi, any update regarding above issue ?
I encountered the same problem. I tried both options (set output_dir with or without "/"), but both failed and showed the same error message. 
```
[sc5006@m006 msisensor]$ msisensor-pro msi -d /manitou/pmg/users/sc5006/data/publicData/msisensor/hg19.reference.site -n /pmglocal/sc5006/data/GDM/DNAseq/bam/IRCR-BT17-1439-T01_B.bam -t /pmglocal/sc5006/data/GDM/DNAseq/bam/IRCR-BT17-1439-T01_T.bam -o .
msi -d /manitou/pmg/users/sc5006/data/publicData/msisensor/hg19.reference.site -n /pmglocal/sc5006/data/GDM/DNAseq/bam/IRCR-BT17-1439-T01_B.bam -t /pmglocal/sc5006/data/GDM/DNAseq/bam/IRCR-BT17-1439-T01_T.bam -o /out_dir
``` 
````
Start at:  Thu Aug 29 17:26:33 2024

loading homopolymer and microsatellite sites ...

Total loading windows:  5804 

Total loading homopolymer and microsatellites:  1786895 

failed to open output files to write !
````

**Comment by pxchen110** [comment]
@agnes-csw Hello, you have to give the output file name instead of the output directory, for example: `-o /out_dir/msi_output.txt`
