### ISSUE TITLE
Why the default value is 1？

### ISSUE THREAD

**Issue by jsonProgram** [xjtu-omics/msisensor-pro#8]
./msisensor_pro pro -h

.
.
-c   <int>      coverage threshold for msi analysis, WXS: 20; WGS: 15, default=1 
.
.
.

best,
json

**Comment by PengJia6** [comment]
> ./msisensor_pro pro -h
> 
> .
> .
> -c coverage threshold for msi analysis, WXS: 20; WGS: 15, default=1
> .
> .
> .
> 
> best,
> json

Sorry for my late answer!  This is a small bug, I used _-c 1_ to debug when developed the software, the default value should be 15. I will  fix it in next realease.  By the way, this parameter is just used to make sure enough reads coverd the analysis sites， and you can change it according to your sequencing coverage data, the 15 and 20 are just empirical value in our test.


best,
Peng

**Comment by PengJia6** [comment]
Hi, Json, @jsonProgram  I have fixed this small bug and you can download the lastest binary file of msisensor-pro [here](https://github.com/xjtu-omics/msisensor-pro/raw/master/binary/msisensor-pro). If you have any other question, please contact with me.
