### ISSUE TITLE
Scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?

### ISSUE THREAD

**Issue by PengJia6** [xjtu-omics/msisensor-pro#9]
Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?

**Comment by zhufengjao** [comment]
Hi Pengjia,
      Recently I have install MSIsenor-pro  and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
      Thanks.

**Comment by zhufengjao** [comment]
> Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?

Hi Pengjia,
Recently I have install MSIsenor-pro and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
Thanks.

**Comment by PengJia6** [comment]
> > Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?
> 
> Hi Pengjia,
> Recently I have install MSIsenor-pro and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
> Thanks.

Sorry！ I will finished this in the following week. Please tell me your email address and I will contact you when I finish it!

**Comment by PengJia6** [comment]
> > Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?
> 
> Hi Pengjia,
> Recently I have install MSIsenor-pro and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
> Thanks.

Sorry！ I will finish it in the following week. Please tell me your email address and I will contact you when I finish it!

**Comment by zhufengjao** [comment]
> > > Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?
> > 
> > 
> > Hi Pengjia,
> > Recently I have install MSIsenor-pro and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
> > Thanks.
> 
> Sorry！ I will finish it in the following week. Please tell me your email address and I will contact you when I finish it!
My email is fengjiaozhu9@163.com.  Thank you very much.

**Comment by PengJia6** [comment]
> > > > Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?
> > > 
> > > 
> > > Hi Pengjia,
> > > Recently I have install MSIsenor-pro and run the tumor_normal.sh for test，then I got the MSI score 9.58% (Number_of_Somatic_Sites %) .Now, How to classify the MSI high and MSI low ? Looking forward to your reply.
> > > Thanks.
> > 
> > 
> > Sorry！ I will finish it in the following week. Please tell me your email address and I will contact you when I finish it!
> > My email is [fengjiaozhu9@163.com](mailto:fengjiaozhu9@163.com).  Thank you very much.

How many samples do you have? And what sequencing technology did you use?  WGS?  WES? or target gene sequencing?

**Comment by Alviner-Heo** [comment]
Hi Pengjia,
Recently I used Msisensor-pro to analyze my RNA-seq data. Msisensor-pro worked fine and got good results. However, I do not know which values to use when checking the MSI status (e.g. MSI-H, MSI-L) from the produced data.
Is there a criteria to check the MSI status from the produced data? I have 290 RNA-seq samples. (Tumor 205 / Normal 85)
Thanks.

**Comment by PengJia6** [comment]
Hi, sorry for late reply. MSIsensor-pro is not recommended for MSI detection with RNA-seq data now.  

But, we have developed a new software named [MSIsensor-RNA](https://github.com/xjtu-omics/msisensor-rna) for RNA expression data.  You can try it, it does not need a cufoff.

**Comment by h170607** [comment]
> Add scripts for user to determine the cuf-off of MSI-H and MSS/MSI-L ?

Why not upload the scripts on GitHub as a complement to msisensor-pro?
